import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")


def _is_configured() -> bool:
    return bool(SMTP_USER and SMTP_PASSWORD)


def send_order_email(order_data: dict, supplier: dict, farm: dict) -> bool:
    """Send a purchase order email to the supplier with a CC to the farm."""
    if not _is_configured():
        print(f"[Email] SMTP not configured. Would send order to {supplier.get('contact_email', 'unknown')}")
        print(f"[Email] Order: {order_data.get('reference_number')} — ${order_data.get('total_price', 0):.2f} NZD")
        return False

    try:
        items = order_data.get("items", [])
        items_html = "".join(
            f"<tr><td style='padding:8px;border-bottom:1px solid #eee'>{i.get('product_name','')}</td>"
            f"<td style='padding:8px;border-bottom:1px solid #eee'>{i.get('quantity','')} {i.get('unit','')}</td>"
            f"<td style='padding:8px;border-bottom:1px solid #eee'>${i.get('unit_price',0):.2f}</td>"
            f"<td style='padding:8px;border-bottom:1px solid #eee'>${i.get('total_price', i.get('quantity',0)*i.get('unit_price',0)):.2f}</td></tr>"
            for i in items
        )
        ref = order_data.get("reference_number", "N/A")
        total = order_data.get("total_price", 0)
        farm_name = farm.get("name", "Unknown Farm")
        farm_email = farm.get("email", SMTP_USER)
        supplier_name = supplier.get("name", "Supplier")
        supplier_email = supplier.get("contact_email")
        contact_name = supplier.get("contact_name", "Sales Team")
        date_str = datetime.now().strftime("%d %B %Y")

        html = f"""
        <html><body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
        <div style="background:#2d6a4f;color:white;padding:20px;border-radius:8px 8px 0 0">
          <h2 style="margin:0">FarmStock AI — Purchase Order</h2>
          <p style="margin:4px 0 0;opacity:0.8">Reference: {ref}</p>
        </div>
        <div style="padding:20px;border:1px solid #eee;border-top:none;border-radius:0 0 8px 8px">
          <p>Dear {contact_name},</p>
          <p>Please find below a purchase order from <strong>{farm_name}</strong> dated {date_str}.</p>
          <table style="width:100%;border-collapse:collapse;margin:16px 0">
            <thead>
              <tr style="background:#f0fdf4">
                <th style="padding:8px;text-align:left">Product</th>
                <th style="padding:8px;text-align:left">Quantity</th>
                <th style="padding:8px;text-align:left">Unit Price</th>
                <th style="padding:8px;text-align:left">Total</th>
              </tr>
            </thead>
            <tbody>{items_html}</tbody>
            <tfoot>
              <tr style="background:#f0fdf4;font-weight:bold">
                <td colspan="3" style="padding:8px;text-align:right">Order Total:</td>
                <td style="padding:8px">${total:.2f} NZD</td>
              </tr>
            </tfoot>
          </table>
          <p>Please confirm this order by replying to this email. A confirmation will be sent to {farm_email}.</p>
          <p style="color:#666;font-size:12px;margin-top:24px">Generated by FarmStock AI — AI-Powered Farm Supply Management</p>
        </div>
        </body></html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Purchase Order {ref} — {farm_name}"
        msg["From"] = f"FarmStock AI <{SMTP_USER}>"
        if supplier_email:
            msg["To"] = supplier_email
        else:
            msg["To"] = SMTP_USER  # fallback: send to sender for testing
        msg["Cc"] = farm_email
        msg["Reply-To"] = farm_email
        msg.attach(MIMEText(html, "html"))

        recipients = [r for r in [supplier_email, farm_email] if r]
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, recipients, msg.as_string())

        print(f"[Email] Order {ref} sent to {supplier_email} (CC: {farm_email})")
        return True

    except Exception as e:
        print(f"[Email] Failed to send order email: {e}")
        return False


def send_custom_order_email(
    to_email: str,
    subject: str,
    body_text: str,
    from_name: str = "FarmStock AI",
    reply_to: str | None = None,
) -> bool:
    """Send a custom plain-text order email to any recipient."""
    if not _is_configured():
        print(f"[Email] SMTP not configured. Would send to {to_email}: {subject}")
        return False
    try:
        msg = MIMEMultipart()
        msg["Subject"] = subject
        msg["From"] = f"{from_name} <{SMTP_USER}>"
        msg["To"] = to_email
        if reply_to:
            msg["Reply-To"] = reply_to
        msg.attach(MIMEText(body_text, "plain"))
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, [to_email], msg.as_string())
        print(f"[Email] Custom order email sent to {to_email}")
        return True
    except Exception as e:
        print(f"[Email] Failed to send custom order email: {e}")
        return False


def send_alert_email(to_email: str, subject: str, body: str) -> bool:
    """Send a plain-text alert email to the farmer."""
    if not _is_configured():
        print(f"[Email] Would send alert to {to_email}: {subject}")
        return False
    try:
        msg = MIMEMultipart()
        msg["Subject"] = subject
        msg["From"] = f"FarmStock AI <{SMTP_USER}>"
        msg["To"] = to_email
        msg.attach(MIMEText(body, "plain"))
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(SMTP_USER, [to_email], msg.as_string())
        return True
    except Exception as e:
        print(f"[Email] Failed to send alert email: {e}")
        return False
