"""
Purchase order email sender via SMTP (smtplib, no third-party email service).
"""
import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime


def send_order_email(order_data: dict, supplier: dict, farm: dict) -> bool:
    """
    Send a formatted HTML purchase order email to the supplier, CC the farm.

    Returns True on success, False on failure.
    """
    smtp_host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", 587))
    smtp_user = os.environ.get("SMTP_USER", "")
    smtp_password = os.environ.get("SMTP_PASSWORD", "")

    supplier_email = supplier.get("contact_email", "")
    farm_email = farm.get("email", "")
    reference = order_data.get("reference_number", "FS-UNKNOWN")
    farm_name = farm.get("name", "Farm")
    supplier_name = supplier.get("name", "Supplier")
    contact_name = supplier.get("contact_name", "Supplier")

    items: list = order_data.get("items", [])
    total_price = order_data.get("total_price", 0.0)
    order_date = datetime.utcnow().strftime("%d %B %Y")

    # Build items table rows
    item_rows = ""
    for item in items:
        product_name = item.get("product_name", "")
        qty = item.get("quantity", 0)
        unit = item.get("unit", "")
        unit_price = item.get("unit_price") or 0.0
        line_total = qty * unit_price
        item_rows += f"""
        <tr>
            <td style="padding:8px;border:1px solid #ddd;">{product_name}</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:center;">{qty} {unit}</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right;">NZD {unit_price:.2f}</td>
            <td style="padding:8px;border:1px solid #ddd;text-align:right;">NZD {line_total:.2f}</td>
        </tr>"""

    html_body = f"""
    <html>
    <body style="font-family:Arial,sans-serif;color:#333;">
        <div style="max-width:650px;margin:auto;padding:24px;border:1px solid #e0e0e0;border-radius:8px;">
            <h2 style="color:#2e7d32;">Purchase Order — {reference}</h2>
            <p>Dear {contact_name},</p>
            <p>
                Please find below a purchase order from <strong>{farm_name}</strong>.
                Kindly confirm receipt and provide an estimated delivery date.
            </p>

            <table style="width:100%;border-collapse:collapse;margin:16px 0;">
                <tr style="background:#f5f5f5;">
                    <th style="padding:8px;border:1px solid #ddd;text-align:left;">Product</th>
                    <th style="padding:8px;border:1px solid #ddd;text-align:center;">Quantity</th>
                    <th style="padding:8px;border:1px solid #ddd;text-align:right;">Unit Price</th>
                    <th style="padding:8px;border:1px solid #ddd;text-align:right;">Line Total</th>
                </tr>
                {item_rows}
                <tr style="font-weight:bold;background:#f5f5f5;">
                    <td colspan="3" style="padding:8px;border:1px solid #ddd;text-align:right;">Total (NZD)</td>
                    <td style="padding:8px;border:1px solid #ddd;text-align:right;">NZD {total_price:.2f}</td>
                </tr>
            </table>

            <table style="width:100%;margin:16px 0;">
                <tr><td style="width:140px;font-weight:bold;">Reference:</td><td>{reference}</td></tr>
                <tr><td style="font-weight:bold;">Order Date:</td><td>{order_date}</td></tr>
                <tr><td style="font-weight:bold;">Farm:</td><td>{farm_name}</td></tr>
                <tr><td style="font-weight:bold;">Region:</td><td>{farm.get('region', '')}</td></tr>
                <tr><td style="font-weight:bold;">Contact Email:</td><td>{farm_email}</td></tr>
                <tr><td style="font-weight:bold;">Delivery:</td><td>Farm address — please contact {farm_email} to confirm delivery details.</td></tr>
            </table>

            <p>Payment terms: 20th of the month following delivery (standard account terms).</p>
            <p>
                This order was generated by <strong>FarmStock AI</strong>.
                For queries, please reply to this email or contact the farm directly at {farm_email}.
            </p>
            <p style="color:#888;font-size:12px;">Ref: {reference} | Generated {order_date}</p>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Purchase Order {reference} — {farm_name}"
    msg["From"] = smtp_user
    msg["To"] = supplier_email
    if farm_email:
        msg["Cc"] = farm_email

    msg.attach(MIMEText(html_body, "html"))

    if not smtp_user or not smtp_password:
        # No SMTP credentials configured — log and return False
        print(f"[email] SMTP not configured. Would send PO {reference} to {supplier_email}")
        return False

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_password)
            recipients = [supplier_email]
            if farm_email:
                recipients.append(farm_email)
            server.sendmail(smtp_user, recipients, msg.as_string())
        print(f"[email] PO {reference} sent to {supplier_email}")
        return True
    except Exception as exc:
        print(f"[email] Failed to send PO {reference}: {exc}")
        return False
